#!/bin/bash

#
# loadprofile - a linux profile laoder
# see: https://github.com/cbuschka/loadprofile.git
#
# update with 
# ```
# curl https://raw.githubusercontent.com/cbuschka/loadprofile/master/loadprofile -o $HOME/bin/loadprofile
# ```
#

LOADPROFILE_PROFILE_DIR=$HOME/profile
LOADPROFILE_MIXINS_DIR=$LOADPROFILE_PROFILE_DIR/profile.d/
LOADPROFILERC=$HOME/.loadprofilerc
LOADPROFILE_EXTRA_DIRS=""

if [ -f "$LOADPROFILERC" ]; then
  source $LOADPROFILERC
fi

function loadprofile_echo() {
  if [ "x${LOADPROFILE_VERBOSE}" = "x1" ]; then
    echo "$@"
  fi
}

function loadprofile_createLink() {
  local tgt=$1
  local src=$2
  if [ -h "$HOME/$src" ] && [ ! -e "$HOME/$src" ]; then \
    rm $HOME/$src
  fi

  if [ ! -e "$HOME/$src" ]; then \
    echo "Linking $tgt..."
    ln -s $LOADPROFILE_PROFILE_DIR/$tgt $HOME/$src
  elif [ -L "$HOME/$src" ]; then
    loadprofile_echo "$HOME/$src is ok."
  else
    echo "Would link $tgt, but $HOME/$src is in the way."
  fi
}

function loadprofile_linkExtraDirs() {
  for d in ${LOADPROFILE_EXTRA_DIRS}; do
    src=$(basename "$d")
    tgt=${LOADPROFILE_PROFILE_DIR}/$d
    loadprofile_createLink $tgt $src
  done
}

function loadprofile_linkDotFiles() {
  for f in $(find $LOADPROFILE_PROFILE_DIR/ -name 'DOT*'); do \
    tgt=$(basename $f)
    src=$(echo $tgt | perl -pe 's#DOT#\.#g')
    loadprofile_createLink $tgt $src
  done
}

function loadprofile_fixPermissions() {
  chmod 700 $LOADPROFILE_PROFILE_DIR
  if [ -d "$LOADPROFILE_PROFILE_DIR/DOTssh" ]; then
    chmod 700 $LOADPROFILE_PROFILE_DIR/DOTssh
    chmod 600 $LOADPROFILE_PROFILE_DIR/DOTssh/*
  fi
}

function loadprofile_loadMixins() {
  if [ ! -d "$LOADPROFILE_MIXINS_DIR" ]; then
    return 0
  fi
  loadprofile_echo -n "Loading..."
  for f in $(find $LOADPROFILE_MIXINS_DIR/ -maxdepth 1 -type f); do
    loadprofile_echo -n " $(basename $f)"
    source $f 2>/dev/null 1>/dev/null
    if [ "x0" != "x${?}" ]; then
      loadprofile_echo -n "!"
    fi
  done
  loadprofile_echo
  return 0
}

function loadprofile_main() {
  if [ ! -d "$LOADPROFILE_PROFILE_DIR" ]; then
    echo "Profile dir $LOADPROFILE_PROFILE_DIR does not exist."
    return 1
  fi

  loadprofile_fixPermissions
  loadprofile_linkDotFiles
  loadprofile_linkExtraDirs
  loadprofile_loadMixins
}

loadprofile_main
